steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/purchased-docker/purchase_predict_api:$SHORT_SHA', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/purchased-docker/purchase_predict_api:$SHORT_SHA']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'purchase-predict-api'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/purchased-docker/purchase_predict_api:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'MLFLOW_TRACKING_URI=$_MLFLOW_SERVER'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/purchased-docker/purchase_predict_api:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
