apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase-predict
  labels:
    app: purchase-predict
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-purchase-predict
  template:
    metadata:
      labels:
        app: pod-purchase-predict
    spec:
      containers:
      - name: pod-purchase-predict
        image: us-central1-docker.pkg.dev/ml-ops-490613/purchased-docker/purchase_predict_api:DOCKER_TAG
        env:
        - name: PORT
          value: "8080"
        - name: ENV
          value: "production"
        - name: MLFLOW_SERVER
          value: "http://136.115.166.98"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "0.5G"
            cpu: "0.5"
          limits:
            memory: "1G"
            cpu: "1"
